; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; [env]
; lib_deps = 
    ; bodmer/TFT_eSPI@^2.5.33
    ; Vector=https://downloads.arduino.cc/libraries/github.com/janelia-arduino/Vector-1.2.2.zip

[env:esp32doit-devkit-v1]
; platform = espressif32
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
build_flags = -Iinclude/ -Isrc/ 
; lib_deps = 
    ; TFT_eSPI=./lib/
    ; TFT_eSPI=https://downloads.arduino.cc/libraries/github.com/Bodmer/TFT_eSPI-2.5.33.zip?_gl=1*1s3l6f5*_ga*NzQ5NTIxMjYyLjE2NDQ0MjAyMzI.*_ga_NEXN8H46L5*MTcwNjY1NDY0OS41My4wLjE3MDY2NTQ2NTIuMC4wLjA.*_fplc*emVEaG5uWTM0RER1c24lMkJJenBXaFIlMkZkRHZGJTJCN1pYTjFodWV2SnNJQnlNY1BlN0g1RjRkVTZlbU9xYkNWS3hobk4yOGJmYUZTOERzU0Y2VUVHUU5wdWlVQkROcXMzcmNGYzNQc0d1JTJCQWdCS3UzVEpQWEUxSDdXJTJGV0hRMVJBZyUzRCUzRA..
    ; Vector=https://downloads.arduino.cc/libraries/github.com/janelia-arduino/Vector-1.2.2.zip